apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: django
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: django
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: django
    spec:
      containers:
      - args:
        - python
        - manage.py
        - runserver
        env:
        - name: DEBUG
          value: "1"
        - name: SECRET_KEY
          value: '")n+tp_1uujeyo!-u^%jm&^hb4kdhsil2pky6^w*y4=wiwqtp&%"'
        image: django
        imagePullPolicy: ""
        name: django
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/app/
          name: django-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: django-claim0
        persistentVolumeClaim:
          claimName: django-claim0
status: {}
